/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.DriverLicenseInfo;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kavita
 */
public class DriverLicInfoCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form DriversLicInfoCreatePanel
     */
    public static DriverLicenseInfo driverLicenseInfoObject;
    private Object file;
    public static String imagePath;
    
    
    public DriverLicInfoCreatePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        driverLicInfo = new javax.swing.JLabel();
        licenseNumber = new javax.swing.JLabel();
        issued = new javax.swing.JLabel();
        expires = new javax.swing.JLabel();
        bloodType = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();
        licenseNoTextField = new javax.swing.JTextField();
        issuedTextField = new javax.swing.JTextField();
        expiresTextField = new javax.swing.JTextField();
        bloodTypeTextField = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        pictureLabel = new javax.swing.JLabel();
        imageButton = new javax.swing.JButton();

        driverLicInfo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        driverLicInfo.setText("Driver's License");

        licenseNumber.setText("License Number");

        issued.setText("Issued");

        expires.setText("Expires");

        bloodType.setText("Blood Type");

        picture.setText("Picture");

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        pictureLabel.setText("view");
        pictureLabel.setPreferredSize(new java.awt.Dimension(50, 70));

        imageButton.setText("Choose image");
        imageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(picture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(imageButton)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issued)
                            .addComponent(licenseNumber)
                            .addComponent(expires)
                            .addComponent(bloodType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(driverLicInfo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(createBtn)
                                .addComponent(expiresTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addComponent(issuedTextField)
                                .addComponent(licenseNoTextField)
                                .addComponent(bloodTypeTextField)))
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(driverLicInfo)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(licenseNumber))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issuedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issued))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiresTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expires))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bloodType))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picture)
                    .addComponent(pictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageButton))
                .addGap(26, 26, 26)
                .addComponent(createBtn)
                .addContainerGap(110, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        String licenseNumber, issued, expires, bloodType, picture;
        licenseNumber=licenseNoTextField.getText().toString();
        issued=issuedTextField.getText().toString();
        expires=expiresTextField.getText().toString();
        bloodType=bloodTypeTextField.getText().toString();
        picture=imagePath;
        
        driverLicenseInfoObject = new DriverLicenseInfo();
        driverLicenseInfoObject.setLicenseNo(licenseNumber);
        driverLicenseInfoObject.setIssued(issued);
        driverLicenseInfoObject.setExpires(expires);
        driverLicenseInfoObject.setBloodType(bloodType);
        driverLicenseInfoObject.setPicture(picture);
        
         JOptionPane.showMessageDialog(null,"Created Sucessfully");
    }//GEN-LAST:event_createBtnActionPerformed

    private void imageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonActionPerformed
        // TODO add your handling code here:
         JFileChooser file = new JFileChooser();
          file.setCurrentDirectory(new File(System.getProperty("user.home")));
          //filter the files
          FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
          file.addChoosableFileFilter(filter);
          int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              imagePath = selectedFile.getAbsolutePath();
              pictureLabel.setIcon(ResizeImage(imagePath));
          }
    }//GEN-LAST:event_imageButtonActionPerformed

 public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(pictureLabel.getWidth(), pictureLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodType;
    private javax.swing.JTextField bloodTypeTextField;
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel driverLicInfo;
    private javax.swing.JLabel expires;
    private javax.swing.JTextField expiresTextField;
    private javax.swing.JButton imageButton;
    private javax.swing.JLabel issued;
    private javax.swing.JTextField issuedTextField;
    private javax.swing.JTextField licenseNoTextField;
    private javax.swing.JLabel licenseNumber;
    private javax.swing.JLabel picture;
    private javax.swing.JLabel pictureLabel;
    // End of variables declaration//GEN-END:variables
}
