/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import business.DemographicInfo;

/**
 *
 * @author Kavita
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private CreatePanel demoJPanel;
    private AddressCreatePanel addressJPanel;
    private SavingAccCreatePanel savingJPanel;
    private CheckingAccCreatePanel checkingPanel;
    private DriverLicInfoCreatePanel driversJPanel;
    private MedicalRecCreatePanel medicalRecJPanel;
    
    /**
     * VIEW NEW FORM MainJframe
     */
      private ViewPanel demoViewJPanel;
    private AddressViewPanel addressViewJPanel;
    private SavingAccViewPanel savingViewJPanel;
    private CheckingAccViewPanel checkingViewPanel;
    private DriverLicInfoViewPanel driversViewJPanel;
    private MedicalRecViewPanel medicalRecViewJPanel;
    
    public static final String DEMOGRAPHIC="demographicInfo";
    public static final String ADDRESS="addressInfo";
    public static final String SAVINGACC="savingAccInfo";
    public static final String CHECKINGACC="checkingAccInfo";
    public static final String DRIVERLICENSE="driverLicenseInfo";
    public static final String MEDICALRECORD="medicalRecord";
    public static final String REPORT="report";
    
    private String selectedItem;
    
    
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        mainMenu = new javax.swing.JMenu();
        demoGraphicItem = new javax.swing.JMenuItem();
        address = new javax.swing.JMenuItem();
        savingAccItem = new javax.swing.JMenuItem();
        checkingAccItem = new javax.swing.JMenuItem();
        driverLicenseItem = new javax.swing.JMenuItem();
        medicalRecordItem = new javax.swing.JMenuItem();
        reportMenu = new javax.swing.JMenu();
        reportItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        jPanel1.add(createButton);

        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewButton);

        jSplitPane3.setLeftComponent(jPanel1);

        getContentPane().add(jSplitPane3, java.awt.BorderLayout.CENTER);

        mainMenu.setText("Menu");
        mainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuActionPerformed(evt);
            }
        });

        demoGraphicItem.setText("Demographic Info");
        demoGraphicItem.setActionCommand("demoItem");
        demoGraphicItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoGraphicItemActionPerformed(evt);
            }
        });
        mainMenu.add(demoGraphicItem);

        address.setText("Address Info");
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        mainMenu.add(address);

        savingAccItem.setText("Saving Account Info");
        savingAccItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingAccItemActionPerformed(evt);
            }
        });
        mainMenu.add(savingAccItem);

        checkingAccItem.setText("Checking Account Info");
        checkingAccItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingAccItemActionPerformed(evt);
            }
        });
        mainMenu.add(checkingAccItem);

        driverLicenseItem.setText("Driver's Lincense Info");
        driverLicenseItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverLicenseItemActionPerformed(evt);
            }
        });
        mainMenu.add(driverLicenseItem);

        medicalRecordItem.setText("Medical Record");
        medicalRecordItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicalRecordItemActionPerformed(evt);
            }
        });
        mainMenu.add(medicalRecordItem);

        jMenuBar2.add(mainMenu);

        reportMenu.setText("Report");
        reportMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportMenuActionPerformed(evt);
            }
        });

        reportItem.setText("View Report");
        reportItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportItemActionPerformed(evt);
            }
        });
        reportMenu.add(reportItem);

        jMenuBar2.add(reportMenu);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuActionPerformed
        // TODO add your handling code here:
        this.add(new CreatePanel());
    }//GEN-LAST:event_mainMenuActionPerformed

    private void reportMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportMenuActionPerformed

    private void demoGraphicItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoGraphicItemActionPerformed
        // TODO add your handling code here:
        selectedItem = DEMOGRAPHIC;
         demoJPanel = new CreatePanel();
        
        jSplitPane3.setRightComponent(demoJPanel);
    }//GEN-LAST:event_demoGraphicItemActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
        selectedItem = ADDRESS;
        addressJPanel = new AddressCreatePanel();
        jSplitPane3.setRightComponent(addressJPanel);
    }//GEN-LAST:event_addressActionPerformed

    private void savingAccItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingAccItemActionPerformed
        // TODO add your handling code here:
        selectedItem = SAVINGACC;
        savingJPanel = new SavingAccCreatePanel();
        jSplitPane3.setRightComponent(savingJPanel);
    }//GEN-LAST:event_savingAccItemActionPerformed

    private void checkingAccItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingAccItemActionPerformed
        // TODO add your handling code here:
        selectedItem = CHECKINGACC;
         checkingPanel = new CheckingAccCreatePanel();
        jSplitPane3.setRightComponent(checkingPanel);
    }//GEN-LAST:event_checkingAccItemActionPerformed

    private void driverLicenseItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverLicenseItemActionPerformed
        // TODO add your handling code here:
        selectedItem = DRIVERLICENSE;
         driversJPanel = new DriverLicInfoCreatePanel();
        jSplitPane3.setRightComponent(driversJPanel);
    }//GEN-LAST:event_driverLicenseItemActionPerformed

    private void medicalRecordItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalRecordItemActionPerformed
        // TODO add your handling code here:
        selectedItem = MEDICALRECORD;
         medicalRecJPanel = new MedicalRecCreatePanel();
        jSplitPane3.setRightComponent(medicalRecJPanel);
    }//GEN-LAST:event_medicalRecordItemActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        if(selectedItem.equalsIgnoreCase(DEMOGRAPHIC)){
          demoJPanel = new CreatePanel();
        
        jSplitPane3.setRightComponent(demoJPanel);  
        }else if(selectedItem.equalsIgnoreCase(ADDRESS)){
             addressJPanel = new AddressCreatePanel();
        jSplitPane3.setRightComponent(addressJPanel);
        }else if(selectedItem.equalsIgnoreCase(SAVINGACC)){
            savingJPanel = new SavingAccCreatePanel();
        jSplitPane3.setRightComponent(savingJPanel);
        }else if(selectedItem.equalsIgnoreCase(CHECKINGACC)){
            checkingPanel = new CheckingAccCreatePanel();
        jSplitPane3.setRightComponent(checkingPanel);
        }else if (selectedItem.equalsIgnoreCase(DRIVERLICENSE)){
            driversJPanel = new DriverLicInfoCreatePanel();
        jSplitPane3.setRightComponent(driversJPanel);
        }else if (selectedItem.equalsIgnoreCase(MEDICALRECORD)){
            medicalRecJPanel = new MedicalRecCreatePanel();
        jSplitPane3.setRightComponent(medicalRecJPanel);
        }
       
    
    }//GEN-LAST:event_createButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        if(selectedItem.equalsIgnoreCase(DEMOGRAPHIC)){
            if(demoViewJPanel==null){
                demoViewJPanel = new ViewPanel();
            }
            
             jSplitPane3.setRightComponent(demoViewJPanel);
             
             demoViewJPanel.displayDemograohicInfo();
             
        }else if(selectedItem.equalsIgnoreCase(ADDRESS)){
            if (addressViewJPanel==null){
                addressViewJPanel = new AddressViewPanel();
            }
             jSplitPane3.setRightComponent(addressViewJPanel);
             
             addressViewJPanel.displayAddress();
        }else if(selectedItem.equalsIgnoreCase(SAVINGACC)){
            if (savingViewJPanel==null){
                savingViewJPanel = new SavingAccViewPanel();
            }
             jSplitPane3.setRightComponent(savingViewJPanel);
             
             savingViewJPanel.displaySavingAcInfo();
        }else if(selectedItem.equalsIgnoreCase(CHECKINGACC)){
            if (checkingViewPanel==null){
                checkingViewPanel = new CheckingAccViewPanel();
            }
             jSplitPane3.setRightComponent(checkingViewPanel);
             
             checkingViewPanel.displayCheckingAcInfo();
        }else if (selectedItem.equalsIgnoreCase(DRIVERLICENSE)){
            if (driversViewJPanel==null){
                driversViewJPanel = new DriverLicInfoViewPanel();
            }
             jSplitPane3.setRightComponent(driversViewJPanel);
             
             driversViewJPanel.displayDriverLicenseInfo();
        }else if (selectedItem.equalsIgnoreCase(MEDICALRECORD)){
            if (medicalRecViewJPanel==null){
                medicalRecViewJPanel = new MedicalRecViewPanel();
            }
             jSplitPane3.setRightComponent(medicalRecViewJPanel);
             
             medicalRecViewJPanel.displayMedicalRecord();
        }
    }//GEN-LAST:event_viewButtonActionPerformed

    private void reportItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportItemActionPerformed
        // TODO add your handling code here:
        jSplitPane3.setRightComponent(new Report());
    }//GEN-LAST:event_reportItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainJFrame().setVisible(true);
             }
        });
    }

    public void addPanels(){
    
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem address;
    private javax.swing.JMenuItem checkingAccItem;
    private javax.swing.JButton createButton;
    private javax.swing.JMenuItem demoGraphicItem;
    private javax.swing.JMenuItem driverLicenseItem;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JMenuItem medicalRecordItem;
    private javax.swing.JMenuItem reportItem;
    private javax.swing.JMenu reportMenu;
    private javax.swing.JMenuItem savingAccItem;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
