/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

/**
 *
 * @author Kavita
 */
public class MedicalRecViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalRecViewPanel
     */
    public MedicalRecViewPanel() {
        initComponents();
    }
    
     public void displayMedicalRecord(){
        String medRecNumber = MedicalRecCreatePanel.medicalRecordObject.getMedRecNumber();
        String allergy1 = MedicalRecCreatePanel.medicalRecordObject.getAllergy1();
        String allergy2 = MedicalRecCreatePanel.medicalRecordObject.getAllergy2();
        String allergy3 = MedicalRecCreatePanel.medicalRecordObject.getAllergy3();
        
        
        medicalRecNumTextField.setText(medRecNumber);
        allergy1TextField.setText(allergy1);
        allergy2TextField.setText(allergy2);
        allergy3TextField.setText(allergy3);
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicalRec = new javax.swing.JLabel();
        medicalRecNumber = new javax.swing.JLabel();
        medicalRecNumTextField = new javax.swing.JTextField();
        allergy1 = new javax.swing.JLabel();
        allergy1TextField = new javax.swing.JTextField();
        allergy2 = new javax.swing.JLabel();
        allergy2TextField = new javax.swing.JTextField();
        allergy3 = new javax.swing.JLabel();
        allergy3TextField = new javax.swing.JTextField();

        medicalRec.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        medicalRec.setText("Medical Record");

        medicalRecNumber.setText("Medical Record Number");

        medicalRecNumTextField.setEditable(false);

        allergy1.setText("Allergy1");

        allergy1TextField.setEditable(false);

        allergy2.setText("Allergy2");

        allergy2TextField.setEditable(false);

        allergy3.setText("Allergy3");

        allergy3TextField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(medicalRec))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(allergy2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(allergy2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(allergy1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(allergy1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(medicalRecNumber)
                                .addGap(44, 44, 44)
                                .addComponent(medicalRecNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(allergy3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(allergy3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(medicalRec)
                                            .addGap(32, 32, 32)
                                            .addComponent(medicalRecNumber))
                                        .addComponent(medicalRecNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(allergy1))
                                .addComponent(allergy1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(allergy2))
                        .addComponent(allergy2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(allergy3)
                        .addComponent(allergy3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(58, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allergy1;
    private javax.swing.JTextField allergy1TextField;
    private javax.swing.JLabel allergy2;
    private javax.swing.JTextField allergy2TextField;
    private javax.swing.JLabel allergy3;
    private javax.swing.JTextField allergy3TextField;
    private javax.swing.JLabel medicalRec;
    private javax.swing.JTextField medicalRecNumTextField;
    private javax.swing.JLabel medicalRecNumber;
    // End of variables declaration//GEN-END:variables
}
