/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.SavingAccountInfo;
import javax.swing.JOptionPane;

/**
 *
 * @author Kavita
 */
public class SavingAccViewPanel extends javax.swing.JPanel {
    private SavingAccountInfo savingAccountInfoObject;

    /**
     * Creates new form SavingAccViewPanel
     */
    public SavingAccViewPanel() {
        initComponents();
    }

     public void displaySavingAcInfo(){
        String bankName = SavingAccCreatePanel.savingAccountInfoObject.getBankName();
        String routingNo = SavingAccCreatePanel.savingAccountInfoObject.getBankRoutingNo();
        String accNo = SavingAccCreatePanel.savingAccountInfoObject.getBankAccNo();
        String balance = SavingAccCreatePanel.savingAccountInfoObject.getAccBalance();
        String accountType = SavingAccCreatePanel.savingAccountInfoObject.getAccType();
        
        bankNameTextField.setText(bankName);
        bankRoutingNoTextField.setText(routingNo);
        bankAccNoTextField.setText(accNo);
        accBalanceTextField.setText(balance);
        accTypetextField.setText(accountType);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        savingAccInfo = new javax.swing.JLabel();
        bankName = new javax.swing.JLabel();
        bankNameTextField = new javax.swing.JTextField();
        bankRoutingNumber = new javax.swing.JLabel();
        bankRoutingNoTextField = new javax.swing.JTextField();
        bankAccountNumber = new javax.swing.JLabel();
        bankAccNoTextField = new javax.swing.JTextField();
        accountBalance = new javax.swing.JLabel();
        accBalanceTextField = new javax.swing.JTextField();
        accountType = new javax.swing.JLabel();
        accTypetextField = new javax.swing.JTextField();

        savingAccInfo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        savingAccInfo.setText("Saving Account");

        bankName.setText("Bank Name");

        bankNameTextField.setEditable(false);

        bankRoutingNumber.setText("Bank Routing Number");

        bankRoutingNoTextField.setEditable(false);

        bankAccountNumber.setText("Bank Account Number");

        bankAccNoTextField.setEditable(false);

        accountBalance.setText("Account Balance");

        accBalanceTextField.setEditable(false);

        accountType.setText("Account Type");

        accTypetextField.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(savingAccInfo)
                .addGap(148, 148, 148))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bankName)
                        .addComponent(bankRoutingNumber)
                        .addComponent(bankAccountNumber)
                        .addComponent(accountBalance)
                        .addComponent(accountType))
                    .addGap(39, 39, 39)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(accTypetextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(accBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bankAccNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bankRoutingNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(savingAccInfo)
                .addContainerGap(256, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(bankName)
                                                .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(bankRoutingNumber))
                                        .addComponent(bankRoutingNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(bankAccountNumber))
                                .addComponent(bankAccNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(accountBalance))
                        .addComponent(accBalanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(accountType)
                        .addComponent(accTypetextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(73, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accBalanceTextField;
    private javax.swing.JTextField accTypetextField;
    private javax.swing.JLabel accountBalance;
    private javax.swing.JLabel accountType;
    private javax.swing.JTextField bankAccNoTextField;
    private javax.swing.JLabel bankAccountNumber;
    private javax.swing.JLabel bankName;
    private javax.swing.JTextField bankNameTextField;
    private javax.swing.JTextField bankRoutingNoTextField;
    private javax.swing.JLabel bankRoutingNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel savingAccInfo;
    // End of variables declaration//GEN-END:variables
}
